{% set python_min = '3.10' %}
{% set name = "hicsv-python" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hicsv-python-{{ version }}.tar.gz
  sha256: 647abc9f93886ca5a61fafb8a843f3f39f27d2aed61969a89cc01368cd54784e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.23
    - python >={{ python_min }}

test:
  imports:
    - hicsv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shntrnkgw/hicsv
  summary: Python implementation of the Header-Included Comma-Separated Values (hicsv) file format.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - shntrnkgw
